### ISSUE TITLE
Is there PCL support?

### ISSUE THREAD

**Issue by kolchy** [markmeeus/MarcelloDB#33]
I would love to try this out (instead of serialising/deserialising my JSON) but not working with my PCL (Xamarin.Forms) project?

Could not install package 'MarcelloDB 0.3.2'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by markmeeus** [comment]
Hi Kolchy,

First of all, thank you for checking out MarcelloDB.

Sure sounds like the use-case marcellodb was designed for.

I think the issue might be wp80, you might have better luck using wp81 instead.

Is supporting wp80 a hard requirement for you? If so, I will gladly look into it.

Also: MarcelloDB is not yet production ready, as I have planned a few (performance related) changes that will make future versions incompatible with data files from older versions.

**Comment by kolchy** [comment]
Hi Mark - and thanks for spending the time to build something like MarcelloDB, I think there is a real need for it :) 👍 

It seems Xamarin.Forms has a requirement on wp80. I've tried creating a new project and set the project as a wp81, but it still doesn't seem to want add the nuget pkg. 

Here is the line from the package.config:

`<package id="Xamarin.Forms" version="2.2.0.5-pre2" targetFramework="portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10" />`

If you can get it running with XF, I think there will be a lot of great use cases for it :) Was thinking of generating the binary data file on a server for the clients to download. Currently I pull down JSON, serialise it and load it which takes precious time. Not fussed if this isn't prod ready yet, I think the use case is perfect, and I'm more than happy to provide feedback/stats/data back to help you keep improving it :)

Cheers,
Karl

**Comment by markmeeus** [comment]
Hi Karl,

Thanks for the thumb :-) I love working on it, although I wish there were more hours in a day :-)

I just released version 0.3.3 on nuget, which should install in you XF PCL library.

Could you confirm if 0.3.3 resolves the issue on your side as well?

I would really appreciate your feedback regarding the server-side generation of the data files. One of the reasons why I decided to support multiple files in a session is exactly for this use case.

Let's use the freshly created google group:
https://groups.google.com/d/forum/marcellodb

**Comment by kolchy** [comment]
AWESOME! Can confirm it now installs, now to test how it performs!

**Comment by markmeeus** [comment]
Package version 0.3.3 on nuget seems to be flawed.
It contains version 0.3.1 assemblies, which have a few very annoying issues. 
You can't persist objects unless they have an ID property for instance.

It's probably best to wait for 0.3.4 which is coming up one of these days.
