### ISSUE TITLE
OutOfMemory exception when accessing from parallel threads

### ISSUE THREAD

**Issue by simbadltd** [markmeeus/MarcelloDB#35]
It seems OutOfMemory may occur in case of two parallel threads (in my case one thread is reading while another thread is writing)

**Comment by markmeeus** [comment]
Hi Simbadltd,

Could you provide me a stacktrace?

**Comment by simbadltd** [comment]
Debugger cannot provide StackTrace because of OutOfMemory. So I am going to write a reproduction test.

**Comment by simbadltd** [comment]
![image](https://cloud.githubusercontent.com/assets/12690849/14560712/2622f468-0333-11e6-83a9-b7443764a106.png)

**Comment by markmeeus** [comment]
Thanks for that.

Normally, the session would block modifications on the data while an enumeration is going on.
It should throw when you try to perform a write operation.

However, it looks like the reading thread ends up with some sort of invalid data.
I'll look into this.

You are not by any chance using different sessions on the same data?

**Comment by simbadltd** [comment]
I'm using wrapper for Session. It's called Database. Database handles one instance of the Session and exposes it as public. Also I have database provider which exposes following field:

```
private static readonly Lazy<IDatabase> _database = new Lazy<IDatabase>(() => new Database(), true);
```

Using "lock()" in all CRUD methods didn't help.

**Comment by markmeeus** [comment]
Hello Simbadltd,

I'm actually having some troubles trying to simulate it. So I looked into the code and may have found a thread-safety issue which may very well cause this crash.

I'll create 0.3.4 which will contain these changes one of these days.

As a sidenote, it looks like you are iterating a collection to find a single object by its name.
This is fine, but you have to be aware that this means you are loading all objects untill one is found.
If your collection is large, you can get a major performance boost by indexing on that Name property.

**Comment by simbadltd** [comment]
Thx, it was a prototype code, of course I will use index in the production code. Waiting for 0.3.4 :)

**Comment by markmeeus** [comment]
I fixed a few multithreading issues in the code, this fix will probably fix your issues too.
I'll leave this issue open until I released 0.3.4 on nuget and you confirmed that it is fixed.

**Comment by markmeeus** [comment]
I just published 0.3.4 on nuget. 
Could you check if this issue is resolved in your scenario as well?

**Comment by simbadltd** [comment]
Works fine

**Comment by markmeeus** [comment]
Awesome! Thanks again for testing.
