### ISSUE TITLE
Wrong version of libraries in nuget package

### ISSUE THREAD

**Issue by simbadltd** [markmeeus/MarcelloDB#36]
I'm encountering with #31 again. So, it is figured out that 0.3.1 libraries have installed with 0.3.3 version nuget-package (Tested both in VS2013 and VS2015).

![image](https://cloud.githubusercontent.com/assets/12690849/14585789/f41a7154-04a3-11e6-85b6-04510bc3edf2.png)

Could you pls check nuget package?

**Comment by simbadltd** [comment]
Workaround: downgrading to 0.3.2 nuget-package

**Comment by markmeeus** [comment]
Great find!

I will remove that version from nuget once 0.3.4 is out.

**Comment by markmeeus** [comment]
0.3.4 was added and 0.3.3 removed.
