### ISSUE TITLE
PCL Support

### ISSUE THREAD

**Issue by PravinPatil27** [markmeeus/MarcelloDB#37]
Can we used this library in PCL project for Xamarin which will be used in Xamarin.iOS and Xamarin.Android projects?

**Comment by markmeeus** [comment]
Hi Pravin,

Yes you can, MarcelloDB is designed to be used like that. It also supports windows 8.1/WP8.1 and up. And regular .net and mono.
This is how you should do it:
1: Install MarcelloDB Package in the PCL, the iOS and the Android project.
2: Create an instance of MarcelloDB Platform in the iOS/Android app.
3: Create the Session in the PCL with the platform-specific Platform instance.

If you have any issues installing or otherwise, I would love to get your feedback on them.
Please also note that MarcelloDB isn't ready for production apps.

**Comment by PravinPatil27** [comment]
Hi Markmeeus,

Thanks for the reply. Which profile should I use in PCL? Right now I am using Profile 111 and I am not able to install MarcelloDB using this profile.

Thanks,
Pravin.

**Comment by markmeeus** [comment]
Hi Pravin,

Could you try with profile 78?

Mark

**Comment by PravinPatil27** [comment]
Hi Mark,

Thanks. Sure, I will try it.

Thanks & Regards,
Pravin Patil.

On Mon, Apr 25, 2016 at 12:11 PM, Mark Meeus notifications@github.com
wrote:

> Hi Pravin,
> 
> Could you try with profile 78?
> 
> Mark
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/markmeeus/MarcelloDB/issues/37#issuecomment-214163947

## 

The information contained in this e-mail may be confidential. It has been 
sent for the sole use of the intended recipient(s). If the reader of this 
message is not an intended recipient, you are hereby notified that any 
unauthorized review, use, disclosure, dissemination, distribution or 
copying of this communication, or any of its contents, 
is strictly prohibited. If you have received it by mistake please let us 
know by e-mail immediately and delete it from your system. Many thanks.

La información contenida en este mensaje puede ser confidencial. Ha sido 
enviada para el uso exclusivo del destinatario(s) previsto. Si el lector de 
este mensaje no fuera el destinatario previsto, por el presente queda Ud. 
notificado que cualquier lectura, uso, publicación, diseminación, 
distribución o copiado de esta comunicación o su contenido está 
estrictamente prohibido. En caso de que Ud. hubiera recibido este mensaje 
por error le agradeceremos notificarnos por e-mail inmediatamente y 
eliminarlo de su sistema. Muchas gracias.

**Comment by PravinPatil27** [comment]
Thanks. I am able install the package in PCL library using profile 78.

**Comment by sorochan** [comment]
Hello! Thanks for work! 
Profile78 is for windows phone silverlight pcl, not windows phone 8.1
Can you add profile111 support?

**Comment by markmeeus** [comment]
Next version (1.0.2) will have support for profile 111.

**Comment by DevEddy** [comment]
Hi Mark,

it's still the same
 
```
Checking compatibility for MarcelloDB 1.0.2 with .NETPortable,Version=v4.5,Profile=Profile111.
Package MarcelloDB 1.0.2 is not compatible with portable45-net45+win8+wpa81 (.NETPortable,Version=v4.5,Profile=Profile111). Package MarcelloDB 1.0.2 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - monotouch (MonoTouch,Version=v0.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-monoandroid10+monotouch10+net45+win+wp8+wp81+xamarinios10+xamarinmac20 (.NETPortable,Version=v0.0,Profile=net45+win+wp80+wp81+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10)
  - portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)
  - xamarinios (Xamarin.iOS,Version=v0.0)
  - xamarinmac (Xamarin.Mac,Version=v0.0)
```

Any Idea?

// EDDY
