### ISSUE TITLE
How to Ignore Properties

### ISSUE THREAD

**Issue by PravinPatil27** [markmeeus/MarcelloDB#38]
Hi Mark,

How to ignore class properties in MarcelloDB? For Sqlite they have ignore attribute but I see only ID attribute in MarcelloDB.

Thanks,
Pravin.

**Comment by PravinPatil27** [comment]
Ooh. I think we can use   [JsonIgnore].

**Comment by markmeeus** [comment]
Hi Pravin,

Yes indeed, [JsonIgnore] should do it.
MarcelloDB uses Json.net internally to serialize objects to Bson. So you can control serialization using the json.net attributes.

**Comment by markmeeus** [comment]
Thanks for testing Pravin!
