### ISSUE TITLE
Store private fields

### ISSUE THREAD

**Issue by simbadltd** [markmeeus/MarcelloDB#39]
Is it possible to store private fields? Or maybe some way for configuring bson serializer exists?

**Comment by markmeeus** [comment]
Hi Simbadltd,

Great to know you are still using MarcelloDB.
Serialization is done using json.net, so you can control a little bit using json.net attributes. However, there is currently no way to include private fields.

Would it be an option to create a class just as storage model and include those fields as public there?

**Comment by simbadltd** [comment]
I'm using it and i'm happy :)

So, what i'm trying to solve is that I want to persist domain object and restore it from storage.
Storage model is a good idea, but I have to introduce another one "sub-layer" for storage models and consequently I have to add mapping infrastructure (factories and so on)

Also, I have the following option:
Hide all internals (which have to be public) with interfaces.

```
public interface IInvestmentCollection
{
   void AddInvestment(Investment investment);
}

public class InvestmentCollection
{
    public List<Investment> Investments { get; set; } // <-- for the sake of persistence it should be public :) We should hide it

   public void AddInvestment(Investment investment)
   {
       // this is domain logic
   }

        internal void CalculatePercentage()
        {
            // this is internal logic. should be called from aggregate.
        }
}

public class Portfolio // this is an aggregate
{
    public IInvestments Investments { get; set; }
}
```

But this option has one big disadvantage: I have to use explicit casting in all places where I need "internals" of domain object:

```
            var investments = (InvestmentCollection)portfolio.Investments;
            investments.LinkWithPortfolio(portfolio);
            investments.CalculatePrice(_investmentPriceCalculatorService);
```

 In theory, all this places should resides in one class and shouldn't spread through the system. But, 
it looks ugly.

I feel that I would go with "storage model" option.

**Comment by markmeeus** [comment]
Yes, I hear you. One of the reasons I'm writing MarcelloDB is to avoid having these kind of mapping layers.

However, there is good news. Storing private properties seems a simple as adding a [JsonProperty] attribute.

``` cs
public class SecretKeeper {
  [JsonProperty()]
  private string MySecret { get; set; } //this property will be stored
}
```

**Comment by simbadltd** [comment]
Great! JsonProperty works as well as other Json serilazer attributes: JsonConstructor (for encapsulating ctor calls), JsonObject (for detecting loop references).
