### ISSUE TITLE
Duplicate index definition for record

### ISSUE THREAD

**Issue by simbadltd** [markmeeus/MarcelloDB#41]
Hi! I'm encountered with strange behavior of indecies.
So, I have a class like this

```
    public sealed class HistoryPoint
    {
        public Guid Id { get; set; }

        public LocalDate Date { get; set; }

        public decimal Price { get; set; }
    }
```

Inside the server code i'm trying to get record of type HistoryPoint from database by date (using index):

```
Collection().Indexes.Date.Find(localDate)
```

And then if record exists i'm trying to update it and save into database.

Then I'm using such code to get all records for the interval:

```
Collection().Indexes.Date.GreaterThanOrEqual(startDate)
```

In some cases, above code can return two records of the single object (ids are identical). It seems that it is bug in index rebuild algorithm. I believe that I don't have duplicated objects in the database, but I have two different(by Reference) duplicated objects in the memory.

P.S. `Collection().All` works well

**Comment by markmeeus** [comment]
Hi Simbadltd, 

Looks like an issue indeed.
The fact that the All method doesn't return the duplicate object indeed means that the index itself somehow got corrupted. One of the reason why this may happen is when the indexed values aren't comparing very well.

Are you using NodaTime? If so I can try to reproduce it. 

As as side note (I haven't documented this yet), the indexing mechanism tries to use a custom serializer for strings, numeric values and DateTime. In this case it will fall back to Bson encoding.
The custom serializer is a lot faster, so if you find performance to be an issue, I would advice you to use a separate property. 
This can be a regular DateTime, or even an Int32 YYYYMMDD.

**Comment by simbadltd** [comment]
Yes, i'm using NodaTime. And it would be nice if i could continue using it. Replacing with DateTime is a kinda of temporary solution.

**Comment by markmeeus** [comment]
I did investigate it a little more.
Right now, NodaTime is not compatible with MarcelloDB because it doesn't json-serialize out of the box.
It looks like it is designed to be immutable, it has a default constructor but the properties Year Month and Day have no setters

The assembly NodaTime.Serialization.JsonNet has extension methods to configure json.net and exposes custom converters as well.

A LocalDate field can be serialized using a JsonConverter attribute, but the same mechanism cannot be applied for the IndexDefinition since the serialized type is constructed from a generic type. 

To support these types I need to find a way for you to configure the json serializer used internally. I'm gonna have to spend some time thinking about how to approach this.

In the meantime you can use this workaround:

First of all, add this helper class.
It converts a LocalDate in an Int, a bit naive, but I guess it does the job.

``` cs
public static class NodaTimeHelper 
{
   public static int AsInt(this LocalDate date)
   {
     return date.Year * 10000 + date.Month * 100 + date.Day;
   }
   public static LocalDate LocalDateFromInt(int intValue)
   {
      var year = intValue / 10000;
      var month =  (intValue / 100) % 100;
      var day = intValue % 100;
      return  new LocalDate(year, month, day);
   }
}
```

Then JsonIgnore the Date field and use the helper to serialize the date as an int

``` cs
public sealed class HistoryPoint
{
  public int Id { get; set; }

    [JsonIgnore]
    public LocalDate Date { get; set; }

    public Int32 DateAsInt { 
      get {                
        return Date.AsInt();
      }
      set{
        this.Date = NodaTimeHelper.LocalDateFromInt(value);
      }
   }
   public decimal Price { get; set; }
}
```

Finally, change your indexdefinition to use the DateAsInt value
Either like this:

``` cs
public class HistoryPointIndexDefinition : IndexDefinition<HistoryPoint>
{        
  public IndexedValue<HistoryPoint, int> DateAsInt { get; set; }
}
```

or like this (if the DateAsInt bothers you)

``` cs
public class HistoryPointIndexDefinition : IndexDefinition<HistoryPoint>
{        
  public IndexedValue<HistoryPoint, int> Date 
  {
    get{
      return base.IndexedValue<int>((point) =>
        {
          return point.DateAsInt;
         });
    }
  }
}
```

Now when using the index (which is now in int field) you'll have to use the helper again:

``` cs
Collection().Indexes.Date.GreaterThanOrEqual(startDate.AsInt())
```

**Comment by simbadltd** [comment]
Am I right that I can use NodaTime for all properties except properties used for index?

**Comment by markmeeus** [comment]
Yes, on indexes, there is no workaround to use LocalDates.
As fields you can use them, but you'll have to use a `JsonConverter` attribute or your LocalDate's wont be serialized properly.

Luckily NodaTime has json.net support to make it a bit easier. (install via nuget NodaTime.Serialization.JsonNet)

Like this:

``` cs
using NodaTime.Serialization.JsonNet;

public class NodaLocalDateConverter : JsonConverter
{
  public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
  {
    NodaConverters.LocalDateConverter.WriteJson(writer, value, serializer);
  }
  public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
  {
    return NodaConverters.LocalDateConverter.ReadJson(reader, objectType, existingValue, serializer);
  }
  public override bool CanConvert(Type objectType)
  {
    return NodaConverters.LocalDateConverter.CanConvert(objectType);
  }
}

public sealed class HistoryPoint
{               
    public Guid Id { get; set; }

    [JsonConverter(typeof(NodaLocalDateConverter))]
    public LocalDate Date { get; set; }

    public decimal Price { get; set; }
}
```

Maybe there is a way to use `NodaConverters.LocalDateConverter`without the need to wrap it but I haven't found it yet :-)

**Comment by simbadltd** [comment]
> As fields you can use them, but you'll have to use a JsonConverter attribute or your LocalDate's wont be serialized properly.

But LocalDate serialization works without custom converter.

**Comment by markmeeus** [comment]
That's bizar, did you somehow configure Json.net globally for NodaTime or something like that?
Maybe it's something platform specific, on which platform (window/ios/android?) are you experiencing the issue?

The thing is that if your LocalDate's are serializing properly, the indexes should work as well. So it's either a serialization issue, or an internal MarcelloDB Indexing issue, it can't be both you see?

If you like, I could look into your code to see what's going on in there? It woud be even better if you could create a project which simulates the issue?

**Comment by markmeeus** [comment]
Hi Simbadltd, 

It's been a while since you opened this issue. Did you find a way to workaround it?
If so, I would like to close the issue.

**Comment by simbadltd** [comment]
Sorry for the delay. I'm using "DateAsInt" as a workaround. All works well. Thx.
