### ISSUE TITLE
Wrong Newtonsoft.Json version

### ISSUE THREAD

**Issue by kameko** [markmeeus/MarcelloDB#42]
Hi. I just downloaded the latest version of MarcelloDB from Nuget, version 0.4.2. When I tried it, it didn't work, it couldn't load Newtonsoft.Json. I investigated a little and noticed Marcello is built against Newtonsoft.Json version 6.0.8, but the Nuget build script depends on 7.0.1. I manually got Newtonsoft.Json version 6.0.8, replaced the binary, and it worked. Just thought you might want to fix this.

**Comment by markmeeus** [comment]
Hi Kameko,

Thank tou for reporting the issue.
I never experienced this issue, but indeed, the versions don't match.

May I ask in what type of project you are using MarcelloDB?

**Comment by markmeeus** [comment]
Json.net dependency has been updated to 9.0.1 in MarcelloDB 0.4.3

Thanks again for the report.
