### ISSUE TITLE
marcelloDB.collections.indexIDValue <> does not contain a definition for setContext

### ISSUE THREAD

**Issue by nkkin** [markmeeus/MarcelloDB#47]
How to fix 
marcelloDB.collections.indexIDvalue does not contain a definition for setContext

also i wanna get all database objects to list to show it in recycleview

**Comment by markmeeus** [comment]
Hi,

Thank you for your interest in MarcelloDB.
Strange error, could you provide a stacktrace please?

**Comment by markmeeus** [comment]
I'm closing this issue since you were not able to provide more details.
