### ISSUE TITLE
Docs should specify sessions need to be disposed due to file locking

### ISSUE THREAD

**Issue by kameko** [markmeeus/MarcelloDB#52]
Just a little quirk I encountered when testing code, a session needs it's Dispose method to be called before the session itself goes out of scope (if it's declared in a method), or else the file is permanently locked until the process ends. I didn't see it anywhere in the docs, so I had to go through the source to find out what exactly I had to call Dispose on. I'd just recommend putting a little footnote on the main page or something about Session needing it's Dispose method called, since the example code makes no hints towards that.

**Comment by markmeeus** [comment]
Hi,

Thanks for reporting this.
I will find a way to get it documented somehow.

The thing is that I would like to avoid people wrapping every transaction in a using block. The idea is to keep the session open.
However, it a test case scenario it makes sense to open new sessions all the time.

I might add a page related to testing in the docs as well

**Comment by kameko** [comment]
Yes, I appreciate the lack of using statements as well. Still, it's good to know about the file locking/Dispose method scenario.

Somewhat related, maybe you can add a new constructor with an argument (default as false) to run a finalizer to free the file instead of having to manually call Dispose. Wouldn't break anything but would add a little extra control.

**Comment by markmeeus** [comment]
I added a few lines to the docs.
Thanks again for reporting this.
