### ISSUE TITLE
Missing some samples - path access exception

### ISSUE THREAD

**Issue by bed007** [markmeeus/MarcelloDB#53]
Hi Mark,

I am testing MarcelloDB with Xamarin. I am struggling with path permissions (on Android at least). I've tried many different "rootPath" for the IPlatform object, all of them failed. I always end up having a :

 System.UnauthorizedAccessException: Access to the path "{rootPath}/journal" is denied.

Can you add a sample or documentation regarding what are the possible values for rootPath as well as which PERMISSIONS we should request in the app manifest ?

Also, please mention any difference between Android and iOS since you are advertising to support Xamarin!

Thanks a lot
Jean

**Comment by Szymaniuk** [comment]
+1 sample project, also with some good example of **session** locking/singleton would be perfect.

**Comment by markmeeus** [comment]
@bed007 Since you reported another issue related to deleting data, I assume you managed to get rid of the UnauthorizedAccessException?
Do you remember what the problem was?

**Comment by bed007** [comment]
@markmeeus : yes I am using System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal) as rootPath

**Comment by markmeeus** [comment]
I added a few lines in the quickstart docs.
Thanks again for reporting.
