### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by Szymaniuk** [markmeeus/MarcelloDB#55]
Is there any plan for .NET Standard support?

**Comment by roubachof** [comment]
I did a pr: #56

**Comment by markmeeus** [comment]
I added a beta version of MarcelloDB 1.0.3 on nuget.
Could you guys try installing it and see if it installs and behaves correctly?

@roubachof if the beta package works, I'm gonna stick with packaging the pcl as the netstandard 1.1. (at least for now)
Thanks again for the PR, but this way will give me less headaches :-)

**Comment by markmeeus** [comment]
I just published a 1.0.3 on nuget.
It should have support for netstandard1.1, fixes support for Universal Windows as well.
