### ISSUE TITLE
Cannot add MarcelloDB to my project

### ISSUE THREAD

**Issue by Daraciel** [markmeeus/MarcelloDB#58]
Hi all.

I'm very interested about using MarcelloDB in my project but i cannot add it through nuget because my profile (259).

¿How can i solve it? ¿Which profiles are supported?

Thanks in advance

**Comment by markmeeus** [comment]
Hi Daraciel,

Currently, MarcelloDB is built for profile 111. In theory I guess i can build it for 259, however, there is no platform support for Silverlight.
Would 111 work for you?

**Comment by Daraciel** [comment]
Thanks! I have changed to profile 111 and it works.

Now i gonna try it. Exists any sample project wich i can see?

Thanks you in advance
