### ISSUE TITLE
Amazing project this might be a replacement for sqlite. is it multi thread

### ISSUE THREAD

**Issue by egarim** [markmeeus/MarcelloDB#59]
Amazing project this might be a replacement for sqlite. is it multi thread?

**Comment by markmeeus** [comment]
Hi Egarim,

Glad you like it.
Marcellodb is definitely thread-safe, so your code can be multithreaded without worrying about access to marcellodb's data.
Internally, marcellodb has an internal lock on all transactions (including read operations). 
This will effectively queue all user threads access to marcellodb.

**Comment by egarim** [comment]
Glad to hear, since with sqlite you can't access the data in 2 threads. will do some test and do a video for my youtube channel. I will let you know when its ready
