### ISSUE TITLE
Xamarin Android Win32 IO returned 25

### ISSUE THREAD

**Issue by egarim** [markmeeus/MarcelloDB#64]
Hi after my xamarin android app has been running for 1 or 2 days I start getting this error while I access the collections

Win32 IO returned 25 Path: /data/user/0/com.myapp/files/Database.dat

there error happened when I call this line

`  Collection<Error, Guid> ErrorCollection { get; set; }`

I'm using Marcello to keep track on errors calling a webservice (if the app is offline), right now I know the file is not that big I only got like 10 records on it. Any idea what is cousin this error ?

**Comment by markmeeus** [comment]
Hi Jose,

Excuse my late response to your other tickets, been busy with other stuff lately.

That's a pretty bizarre exception you got there. It looks like MarcelloDB is trying to read after the end of the file or something, which should not be happening at all.
Just to be sure, could you check that the path to the file is correct, and also correctly formatted? I have seen reports of this error (25) when paths used \ as separator on Ubuntu.

If the problem persists, would you mind sending me a copy of the database so I can inspect the issue?

**Comment by egarim** [comment]
Hi Mark 
I was not able to retrieve the file but I will keep you posted in case this error appears again.Also there was only one collection which throw that error(Win32 IO returned 25), all the other collections work fine
