### ISSUE TITLE
Add item to collection without an ID

### ISSUE THREAD

**Issue by WashingtonARamos** [markmeeus/MarcelloDB#65]
Is there any way to add an item (object) to a collection without the need to provide an ID?

MongoDB have this option in which MongoDB itself generates a random string to be used as the ID of that object.

**Comment by markmeeus** [comment]
Hi, 

Thank you for your interest in MarcelloDB.
For now, there is no such feature in MarcelloDB. I would like to keep MarcelloDB as lightweight as possible.

The easiest way to achieve what you want is to have a base class which creates a new guid in its contstructor, and have a get/set property to access it.
This way, when you create a new instance, it will have a new Id, but when you load it from your server, or MarcelloDb, the serializer will set it's property correctly.

Hope this helps
