### ISSUE TITLE
Slow access to the collection after create indexes 

### ISSUE THREAD

**Issue by egarim** [markmeeus/MarcelloDB#71]
Hi 
after I created indexes over a string field on a Marcello collection the loading time of the date increased. In my code, I load the collection by pages using the following code

                      var Result = CarsCollection.Skip(numberOfObjectsPerPage * CurrentPage)
                      .Take(numberOfObjectsPerPage);

after I added an index the execution time of the code above increased more than 10 times

is that a side effect of using indexes?

**Comment by markmeeus** [comment]
Hi Jose,

That's pretty bizar, it should not have any impact on reading times at all. Inserts and updates will get a bit slower for every index added, but even then it's not a tenfold.

From your code I can't see what CarsCollection actually is, I'm guessing it's the All enumeration?
If so you have to understand that the Skip() actually enumerates all data, and therefore it needs to load that data from the files.
This would definitely become slow as the pages increase.

If you need paging, you would be better of using an index and then the GreaterThan Enumeration, this will avoid loading all previous objects.

```cs
CarsCollection.Indexes.SomeSortValue.GreaterThan(lastValueFromPreviousPage).Skip(numberOfObjectsPerPage)
```

Another option would be to keep a reference to the enumeration and use that one under the hood. 
```cs
var enum = CarsCollection.All.GetEnumerator();
```

And then use enum.Next and enum.Current to fetch the next 'pageSize' objects. However, this approach will block you from doing modifications, so calls to Persist will throw an error.

**Comment by markmeeus** [comment]
HI Jose,

Did you manage to speed it up?
