### ISSUE TITLE
.netfx not found

### ISSUE THREAD

**Issue by champcbg** [markmeeus/MarcelloDB#76]
i added the MarcelloDB  nuget package to xamarin.ios, xamarin.droid, and the shared project.

when i call this line.  

`  var platform = MarcelloDB.netfx.Platform();`

this error is thrown

**The type or namespace name 'netfx' does not exist in the namespace 'MarcelloDB'**

not sure what is missing.

**Comment by DevEddy** [comment]
You need to call this code in your platform code

For Android and iOS:
```csharp
new MarcelloDB.netfx.Platform ();
```
For UWP:
```chsarp
new MarcelloDB.uwp.Platform()
```

You could create an interface and implement it based on the platform you need:

### Shared code
```csharp
public interface IMarcelloPlatform
{
    IPlatform Platform { get; }
}
```

### iOS sample implementation
```csharp
using System;
using System.IO;
using MarcelloDB.Platform;

[assembly: Xamarin.Forms.Dependency(typeof(MarcelloPlatform))]
namespace CloudMatic.iOS.Implementations
{
    [Xamarin.Forms.Internals.Preserve(AllMembers = true)]
    public class MarcelloPlatform : IMarcelloPlatform
    {
        public IPlatform Platform => new MarcelloDB.netfx.Platform();
    }
}
```

Then you could initialize the Session
```csharp
// Resolve the dependecy
var marcelloPlatform = DependencyService.Get<IMarcelloPlatform>()

var session = new Session(marcelloPlatform.Platform, "YourDbPath");
var collectionFile = Session["Name"];
```

**Comment by markmeeus** [comment]
Thanks Eduard, for the explanation!
@champcbg did you manage to resolve your issue?

**Comment by champcbg** [comment]
@markmeeus, @DevEddy  yes it help, and got me completely past the issue.  Apologies for not responding quicker, once i got it working i got lost in writing code again.
